# CodeRabbit Configuration
# このファイルはCodeRabbitの動作を設定します

reviews:
  # レビューの詳細度（assertive: 指摘多め, chill: 控えめ）
  profile: chill

  # PR サマリーの自動生成を有効化
  high_level_summary: true

  # レビュー対象から除外するパスを指定
  path_filters:
    # 自動生成されるAPIタイプファイル（swagger-typescript-api生成）
    - '!frontend/src/api/types/Api.ts'
    - '!frontend/src/api/types/Auth.ts'
    - '!frontend/src/api/types/data-contracts.ts'
    - '!frontend/src/api/types/http-client.ts'
    # 自動生成されるSwagger関連ファイル
    - '!backend/src/swagger-schemas.ts'
    - '!backend/swagger-output.json'
    - '!docs/index.html'

  # ツール設定
  tools:
    # CIで検知されるエラーは重複してコメントしないようにESLintのみ無効化
    eslint:
      enabled: false
    semgrep:
      enabled: true
    oxc:
      enabled: true
    yamllint:
      enabled: true

  # レビュー全体への追加指示
  instructions: |
    CIで検知されるESLintエラーにはコメントせず、高レベルなフィードバックに集中してください。
