# To start postgresql server for development, run `make up`
up:
	docker-compose up -d

# To stop postgresql server for development, run `make down`
down:
	docker-compose down

# To delete all data in the database, run `make destroy`
destroy:
	docker-compose down -v