# To start postgresql server for development, run `make start-db`
start-db:
	docker-compose up -d

# To stop postgresql server for development, run `make stop-db`
stop-db:
	docker-compose down

# To delete all data in the database, run `make clean-db`
clean-db:
	docker-compose down -v