#!/usr/bin/env bash

cd backend

# ERDとRedocを生成
npm run generate-erd && npm run redoc

cd ..

# 変更されたファイルをステージングに追加
if [ -f "docs/index.html" ]; then
  git add docs/index.html
  echo "✨ Added docs/index.html to staging"
fi

if [ -f "backend/erd.svg" ]; then
  git add backend/erd.svg
  echo "✨ Added backend/erd.svg to staging"
fi

# 正常終了
exit 0
