#!/usr/bin/env bash

# Run only when backend files are staged
if ! git diff --cached --name-only | grep -q '^backend/'; then
  exit 0
fi

cd backend

# ERDとRedocを生成
npm run generate-erd && npm run redoc && npm run generate-api-types

cd ..

# 変更されたファイルをステージングに追加
if [ -f "docs/index.html" ]; then
  git add docs/index.html
  echo "✨ Added docs/index.html to staging"
fi

if [ -f "backend/erd.svg" ]; then
  git add backend/erd.svg
  echo "✨ Added backend/erd.svg to staging"
fi

# frontend/src/api/types配下に生成されたファイルをステージングに追加
for file in frontend/src/api/types/*; do
  if [ -f "$file" ]; then
    git add "$file"
    echo "✨ Added $file to staging"
  fi
done

# 正常終了
exit 0
