name: Backend Test

# このワークフローが実行される条件:
# 1. developブランチをターゲットとするPR時（feature→develop PR）
# 2. mainブランチをターゲットとするPR時（develop→main PR）
#
# 開発フロー想定:
# feature branch → develop (PR) → main (PR)
# developへの直接pushは行わないため、pull_requestイベントのみで十分
on:
  pull_request:
    branches:
      - develop  # developをターゲットとするPR時に実行（feature→develop PR）
      - main     # mainブランチをターゲットとするPR時に実行（develop→main PR）
    paths:
      - 'backend/**'  # バックエンドディレクトリ内のファイル変更時のみ
      - '.github/workflows/backend-test.yml'  # このワークフローファイル自体の変更時

jobs:
  backend-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run backend tests
        working-directory: ./backend
        run: npm run test

      - name: Run backend test coverage
        working-directory: ./backend
        run: npm run test -- --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./backend/coverage/lcov.info
          flags: backend
          name: backend-coverage
          fail_ci_if_error: false
