name: Create develop to main PR

on:
  push:
    branches:
      - develop
  workflow_dispatch: # Allow manual triggering for maintenance and debugging

permissions:
  contents: read
  pull-requests: write

jobs:
  create_pr:
    concurrency:
      group: 'create-develop-to-main'
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if PR exists
        id: check_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:develop`,
              base: 'main'
            });
            
            if (pulls.length > 0) {
              console.log('PR already exists. Skipping PR creation.');
              return 'true';
            }
            
            return 'false';

      - name: Create Pull Request
        if: steps.check_pr.outputs.result == 'false'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_GITHUB_TOKEN }}
          script: |
            const { data: pull } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'develop to main',
              body: 'Automatically created PR from develop to main branch',
              head: 'develop',
              base: 'main'
            });
            
            console.log(`Pull request created: ${pull.html_url}`);
