name: Frontend Lint

# このワークフローが実行される条件:
# 1. developブランチをターゲットとするPR時（feature→develop PR）
# 2. mainブランチをターゲットとするPR時（develop→main PR）
# 
# 開発フロー想定:
# feature branch → develop (PR) → main (PR)
# developへの直接pushは行わないため、pull_requestイベントのみで十分
on:
  pull_request:
    branches:
      - develop  # developをターゲットとするPR時に実行（feature→develop PR）
      - main     # mainブランチをターゲットとするPR時に実行（develop→main PR）
    paths:
      - 'frontend/**'  # フロントエンドディレクトリ内のファイル変更時のみ
      - '.github/workflows/frontend-lint.yml'  # このワークフローファイル自体の変更時

jobs:
  frontend-lint:
    uses: ./.github/workflows/npm-run.yml
    permissions:
      contents: read
    with:
      working-directory: ./frontend
      run: npm run lint
