# .github/workflows/issue_notifications.yml
name: Issue Notifications

on:
  issues:
    types: [opened, closed]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          ACTION: ${{ github.event.action }}
          NUMBER: ${{ github.event.issue.number }}
          TITLE: ${{ github.event.issue.title }}
          URL: ${{ github.event.issue.html_url }}
        uses: actions/github-script@v7
        with:
          script: |
            try {
              // 通知タイプに応じて文言と色を切り替え
              const content = process.env.ACTION === 'opened' 
                ? ':sparkles: New issue created'
                : ':lock: Issue closed';
              
              const color = process.env.ACTION === 'opened'
                ? 3066993  // 緑
                : 15158332; // 赤
              
              // Discord 向けペイロードを作成
              const payload = {
                content: content,
                embeds: [{
                  title: `#${process.env.NUMBER} ${process.env.TITLE}`,
                  url: process.env.URL,
                  color: color
                }]
              };
              
              // Discord webhook に fetch API を使用してリクエストを送信
              const response = await fetch(process.env.DISCORD_WEBHOOK_URL, {
                method: 'POST',
                headers: {
                  'Content-Type': 'application/json'
                },
                body: JSON.stringify(payload)
              });
              
              if (!response.ok) {
                throw new Error(`Discord API responded with status: ${response.status}`);
              }
              
              console.log('Discord notification sent successfully');
            } catch (error) {
              console.error('Failed to send Discord notification:', error);
              core.setFailed(error.message);
            }
