# .github/workflows/issue_notifications.yml
name: Issue Notifications

# このワークフローが実行される条件:
# GitHubのIssueに対する以下のアクション時に実行される
# - opened: 新しいIssueが作成された時
# - closed: Issueがクローズされた時
# 目的：Issue の状態変更をDiscordに自動通知する
on:
  issues:
    types: [opened, closed]  # Issue作成時とクローズ時にDiscord通知

permissions:
  issues: read

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send notification to Discord
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          ACTION: ${{ github.event.action }}
          NUMBER: ${{ github.event.issue.number }}
          TITLE: ${{ github.event.issue.title }}
          URL: ${{ github.event.issue.html_url }}
          BODY: ${{ github.event.issue.body }}
          REPO: ${{ github.repository }}
        run: node .github/scripts/notify-discord.js
