name: npm run

on:
  workflow_call:
    inputs:
      working-directory:
        description: Directory where npm commands run
        required: true
        type: string
      run:
        description: Command to execute
        required: true
        type: string
      coverage-file:
        description: Optional coverage file path for Codecov upload
        required: false
        type: string
      codecov-flags:
        description: Flags for Codecov
        required: false
        type: string
      codecov-name:
        description: Name for Codecov upload
        required: false
        type: string

jobs:
  npm-run:
    runs-on: ubuntu-latest
    # Permissions are controlled by the caller workflow.
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: "${{ inputs.working-directory }}/package-lock.json"

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: npm ci

      - name: Run command
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.run }}

      - name: Upload coverage reports to Codecov
        if: inputs.coverage-file != ''
        uses: codecov/codecov-action@v4
        with:
          files: ${{ inputs.coverage-file }}
          flags: ${{ inputs.codecov-flags }}
          name: ${{ inputs.codecov-name }}
          fail_ci_if_error: false
          use_oidc: true
